/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sss2nd;

import java.io.File;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.Set;
import javax.crypto.BadPaddingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public gui() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btn_keygen = new javax.swing.JButton();
        btn_encrypt = new javax.swing.JButton();
        btn_browse = new javax.swing.JButton();
        txt_keypath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_input = new javax.swing.JTextArea();
        btn_decrypt = new javax.swing.JButton();
        enc_priv = new javax.swing.JRadioButton();
        enc_pub = new javax.swing.JRadioButton();
        dec_priv = new javax.swing.JRadioButton();
        dec_pub = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));

        btn_keygen.setText("Generate Key ");
        btn_keygen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keygenActionPerformed(evt);
            }
        });

        btn_encrypt.setText("Encrypt");
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });

        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        txt_keypath.setEditable(false);

        jLabel1.setText("Choose a Path to generate Key Pair ");

        jLabel2.setText("Encrypt/ Decrypt");

        txt_input.setColumns(20);
        txt_input.setRows(5);
        jScrollPane1.setViewportView(txt_input);

        btn_decrypt.setText("Decrypt");
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });

        buttonGroup1.add(enc_priv);
        enc_priv.setSelected(true);
        enc_priv.setText("Private Key");

        buttonGroup1.add(enc_pub);
        enc_pub.setText("Public Key");

        buttonGroup2.add(dec_priv);
        dec_priv.setText("Private Key");

        buttonGroup2.add(dec_pub);
        dec_pub.setSelected(true);
        dec_pub.setText("Public Key");

        txt_output.setEditable(false);
        txt_output.setColumns(20);
        txt_output.setRows(5);
        txt_output.setWrapStyleWord(true);
        txt_output.setOpaque(false);
        jScrollPane2.setViewportView(txt_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(btn_keygen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txt_keypath, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_browse))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_encrypt)
                                .addGap(18, 18, 18)
                                .addComponent(enc_priv)
                                .addGap(18, 18, 18)
                                .addComponent(enc_pub))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_decrypt)
                                .addGap(18, 18, 18)
                                .addComponent(dec_priv)
                                .addGap(18, 18, 18)
                                .addComponent(dec_pub))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keypath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse)
                    .addComponent(btn_keygen))
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_encrypt)
                            .addComponent(enc_priv)
                            .addComponent(enc_pub))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_decrypt)
                            .addComponent(dec_priv)
                            .addComponent(dec_pub))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keygenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keygenActionPerformed

        if (txt_keypath.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Select the path to generate the keys");
        } else {
            String path_pub = txt_keypath.getText() + "/publicKey";
            String path_priv = txt_keypath.getText() + "/privateKey";
            File f1 = new File(path_pub);
            File f2 = new File(path_priv);
            int file_exist = -1;
            if (f1.exists() || f2.exists()) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                file_exist = JOptionPane.showConfirmDialog(null, "Private key or Public key is already existing in the path. Do you want to overwrite it?", "Warning", dialogButton);
                if (file_exist == JOptionPane.YES_OPTION) {

                }
            }
            if (file_exist == -1 || file_exist == 0) {

                keygen gk;
                try {
                    gk = new keygen(1024);
                    gk.ckey();
                    gk.writeToFile(path_pub, gk.getPublicKey().getEncoded());
                    gk.writeToFile(path_priv, gk.getPrivateKey().getEncoded());
                    JOptionPane.showMessageDialog(null, "Key Pair Successfully Created");
                } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
                    System.err.println(e.getMessage());
                } catch (IOException e) {
                    System.err.println(e.getMessage());
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_keygenActionPerformed

    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed

        try {

            sss2nd ac = new sss2nd();
            String path_pub = txt_keypath.getText() + "/privateKey";
            String path_priv = txt_keypath.getText() + "/publicKey";
            File a = new File(path_pub);
            File b = new File(path_priv);
            if (!a.exists() || !b.exists()) {
                JOptionPane.showMessageDialog(null, "Private key or Public key not exist in the given path. Generate the key pair");
            } else {
                String msg = txt_input.getText();
                if (enc_priv.isSelected()) {
                    PrivateKey privateKey = ac.getPrivate(path_pub);
                    String encrypted_msg = ac.encryptText(msg, privateKey);
                    txt_output.setText(encrypted_msg);
                } else if (enc_pub.isSelected()) {
                    PublicKey publicKey = ac.getPublic(path_priv);
                    String encrypted_msg = ac.encryptText(msg, publicKey);
                    txt_output.setText(encrypted_msg);
                }

            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_encryptActionPerformed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        fileChooser.setAcceptAllFileFilterUsed(false);

        int rVal = fileChooser.showOpenDialog(null);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            txt_keypath.setText(fileChooser.getSelectedFile().toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_browseActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed

        try {

            sss2nd ac = new sss2nd();
            String path_pub = txt_keypath.getText() + "/privateKey";
            String path_priv = txt_keypath.getText() + "/publicKey";
            File f1 = new File(path_pub);
            File f2 = new File(path_priv);
            if (!f1.exists() || !f2.exists()) {
                JOptionPane.showMessageDialog(null, "Private key or Public key not exist in the given path. Generate the key pair");
            } else {
                String msg = txt_input.getText();
                if (dec_priv.isSelected()) {
                    PrivateKey privateKey = ac.getPrivate(path_pub);
                    String decrypted_msg = ac.decryptText(msg, privateKey);
                    txt_output.setText(decrypted_msg);
                } else if (dec_pub.isSelected()) {
                    PublicKey publicKey = ac.getPublic(path_priv);
                    String decrypted_msg = ac.decryptText(msg, publicKey);
                    txt_output.setText(decrypted_msg);
                }
            }
        } catch (BadPaddingException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_keygen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton dec_priv;
    private javax.swing.JRadioButton dec_pub;
    private javax.swing.JRadioButton enc_priv;
    private javax.swing.JRadioButton enc_pub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_input;
    private javax.swing.JTextField txt_keypath;
    private javax.swing.JTextArea txt_output;
    // End of variables declaration//GEN-END:variables
}
